using QuickSalesApp.Domain.AppEntities.CompanyEntities;
using QuickSalesApp.Domain.Repositories.Company.BankBankAccountRepositories;
using QuickSalesApp.Persistance.Repositories.GenericRepositories.CompanyDbRepositories;

namespace QuickSalesApp.Persistance.Repositories.CompanyDbRepositories.BankBankAccountRepositories;

public sealed class BankBankAccountQueryRepository : CompanyDbQueryRepository<BankBankAccount>, IBankBankAccountQueryRepository
{
}
